### ISSUE TITLE
Trova aula libera

### ISSUE THREAD

**Issue by silviascantamburlo** [FrancyFiore/Find-my-Aula#1]
Come utente voglio trovare un’aula libera così da poter avere uno spazio alternativo alla biblioteca dove poter studiare e confrontarmi anche con i miei compagni. Le aule libere verranno segnale nella mappa con diversi colori in base se sono libere (verde), non sono libere (rosse) e se sono libere solo per un breve periodo (gialle).

HTD: Partendo dalla pagina principale, quando sceglierò l’opzione “Trova aula libera” e avrò inserito uno slot di tempo, mi sarà mostrata una lista delle aule libere in quella determinata fascia temporale.

**Comment by FrancyFiore** [comment]
This issue was moved to FrancyFiore/Find-my-Aula2#1
