### ISSUE TITLE
Trova lezione

### ISSUE THREAD

**Issue by silviascantamburlo** [FrancyFiore/Find-my-Aula#3]
Come utente voglio sapere in che aula si svolge una determinata lezione in modo tale da non dover sfogliare gli orari di tutte le aule per poter trovare l’aula della lezione che cerco.

HTD: Partendo dalla pagina principale, quando scriverò il nome della lezione che desidero seguire nell’apposito slot di testo e darò l’invio, mi sarà mostrata l’aula dove tale lezione si svolge e evidenziata sulla mappa dell’edificio.

**Comment by FrancyFiore** [comment]
This issue was moved to FrancyFiore/Find-my-Aula2#3
