### ISSUE TITLE
Mostra orario

### ISSUE THREAD

**Issue by silviascantamburlo** [FrancyFiore/Find-my-Aula#4]
Come utente voglio vedere l’orario di una determinata aula per sapere quali lezioni si svolgeranno in una determinata giornata.

HTD: Partendo dalla pagina principale, quando scriverò il nome dell’aula nell’apposito slot di testo e la data del giorno di cui sono interessato e darò l’invio, mi sarà mostrato l’elenco delle lezioni in quell’aula della giornata scelta.

**Comment by FrancyFiore** [comment]
This issue was moved to FrancyFiore/Find-my-Aula2#4
